# read csv printers
- name: read printers from csv file
  set_fact:
    printersfile: "{{ lookup('file', tasks_cups_printers_csv) }}"

- name: csv to list
  set_fact:
    printers: "{{ printersfile.split('\n') }}"

- name: Initialize an empty list for our printers
  set_fact:
    cups_printer_list: []

- name: monta lista de dicionÃ¡rios cups_printer_list
  set_fact: 
    cups_printer_list: > 
      {{ cups_printer_list + [{ 
        'name': item.split(',')[0], 
        'uri': 'socket://'+item.split(',')[1],
        'printer_or_class': 'printer',
        'state': 'present',
        'location': item.split(",")[0],
        'info': item.split(",")[0]
      }]}}
  with_items:
    - "{{ printers }}"

